[package]
name = "rust-blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
parity-scale-codec = { version = "3.6.9", features = ["derive", "bit-vec"] }
subxt = "0.35.0"
tokio = { version = "1.37.0", features = ["rt", "rt-multi-thread"] }
